# .streamlit/pages_sections.toml


[[pages]]
path = "paginas//Mapa.py"
name = "Mapa de EstaÃ§Ãµes"
icon = "ğŸ“"

[[pages]]
path = "paginas//Normas.py"
name = "Banco de Normas"
icon = "ğŸ“"

[[pages]]
name = "Estudo de Ampacidade"
icon = "âš¡"
is_section = true   # <<< Indica que este item NÃƒO Ã© pÃ¡gina e sim um tÃ­tulo de seÃ§Ã£o

[[pages]]
path = "paginas//Ampacidade//Dadosdeentrada.py"
name = "Dados de Entrada"
icon = "ğŸ“‹"

[[pages]]
path = "paginas//Ampacidade//RiscoTermico.py"
name = "Ver Risco TÃ©rmico"
icon = "ğŸŒ¡ï¸"

[[pages]]
path = "paginas//Ampacidade//IntervalosDeMedicao.py"
name = "Ver intervalos de MediÃ§Ã£o"
icon = "ğŸ“ˆ"

[[pages]]
name = "Estudo de Clima"
icon = "â˜ï¸"
is_section = true 

[[pages]]
path = "paginas//Clima//Clima.py"
name = "Dados de Entrada"
icon = "ğŸ“‹"
